{% set name = "mdaencore" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdaencore-{{ version }}.tar.gz
  sha256: 82ea52998edb1bdf797736c054eb6e3caa8f48d6b5972fe10d48f7f353ff8f52

build:
  skip: true  # [py>314]
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=61.2
    - wheel
    - cython
    - numpy  {{ numpy }}
    - pip
  run:
    - python
    - mdanalysis >=2.1.0
    - joblib
    - scipy

test:
  imports:
    - mdaencore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MDAnalysis/mdaencore
  summary: Ensemble overlap comparison software for molecular data.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - enoee
    - IAlibay
    - ianmkenney
    - orbeckst
